spring:
  application:
    name: yukihira-bookstore
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    url: ${DIRECT_URL:${DATABASE_URL}}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    locations: classpath:db/migration
  thymeleaf:
    cache: false
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
